spring.datasource.url= jdbc:sqlserver://103.69.84.136:1433;trustServerCertificate=true;DatabaseName=WFOTest3;Connection Timeout=30
spring.datasource.username= sa
spring.datasource.password= LYedPenhmPJP2nw2

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect